name: Builds upon PR

on: pull_request

jobs:
  build-and-push:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          tags: |
            smartcontract/builder:latest
          platforms: linux/386,linux/amd64,linux/arm64
